#!/usr/bin/env python3
"""调试验证逻辑"""

import sys

sys.path.append(".")

from final_prompt_collector import StrictPromptExtractor

extractor = StrictPromptExtractor()

test_prompts = [
    "professional headshot, confident male executive, 40s, sharp jawline, neutral background, Rembrandt lighting, business attire, Hasselblad medium format quality, highly detailed, 8k resolution",
    "high fashion editorial portrait, androgynous model, avant-garde makeup, Vogue magazine aesthetic, dramatic shadows, high contrast, shot on Leica M, professional fashion photography, 8k",
]

for prompt in test_prompts:
    print(f"\n测试提示词: {prompt[:80]}...")
    text_lower = prompt.lower()

    # 检查非提示词排除
    non_prompt = [
        "http://",
        "https://",
        "www.",
        ".com",
        ".org",
        ".net",
        "browserslist",
        "not ie <=",
        "def ",
        "function ",
        "class ",
        "import ",
        "export ",
        "install ",
        "setup ",
        "configuration",
        "license",
        "repository",
        "collection",
        "notebook",
        "technique",
        "transform",
        "create",
        "generate",
        "control",
        "movement",
        "ws://",
        "api/",
        "endpoint",
        "route",
        # 技术文档词汇
        "parameter",
        "parameterization",
        "required",
        "optional",
        "default",
        "browser",
        "startup",
        "warrant",
        "warranty",
        "condition",
        "basis",
        "models",
        "model",
        "version",
        "update",
        "change",
        "bug",
        "fix",
        "issue",
        "pull request",
        "commit",
        "merge",
        "branch",
        "release",
        "dependency",
        "package",
        "npm",
        "yarn",
        "pip",
        "install",
        "documentation",
        "readme",
        "changelog",
        "contributing",
        "license",
        "mit",
        "apache",
        "gpl",
        "copyright",
        "author",
        "test",
        "testing",
        "unit test",
        "integration",
        "ci",
        "cd",
        "docker",
        "container",
        "kubernetes",
        "deploy",
        "production",
        "development",
        "environment",
        "variable",
        "config",
        "setting",
        "log",
        "debug",
        "error",
        "warning",
        "info",
        "exception",
        "stack",
        "trace",
        "crash",
        "failure",
        "success",
        "status",
        "code",
        "source",
        "binary",
        "executable",
        "compiler",
        "interpreter",
        # 更多技术文档词汇
        "caching",
        "cache",
        "database",
        "query",
        "queries",
        "redis",
        "application",
        "layer",
        "error",
        "errors",
        "fail",
        "fails",
        "failure",
        "failures",
        "invalidation",
        "stale",
        "indication",
        "gracefully",
        "logged",
        "break",
        "means",
        "data",
        "remain",
        "changelog",
        "keep a changelog",
        "format",
        "based on",
        "the format is based",
        "all notable changes",
        # 系统和技术术语
        "system",
        "software",
        "hardware",
        "network",
        "server",
        "client",
        "user",
        "users",
        "admin",
        "administrator",
        "permission",
        "authentication",
        "authorization",
        "security",
        "encryption",
        "performance",
        "optimization",
        "scalability",
        "reliability",
        "availability",
        "maintenance",
        "backup",
        "restore",
        "recovery",
        # 项目管理术语
        "project",
        "task",
        "milestone",
        "deadline",
        "schedule",
        "budget",
        "resource",
        "team",
        "collaboration",
        "communication",
        "meeting",
        "agenda",
        "minutes",
        "report",
        "dashboard",
        "metrics",
    ]

    # 检查是否包含非提示词内容
    for indicator in non_prompt:
        if indicator in text_lower:
            print(f"  包含非提示词: {indicator}")

    # 检查句子结构
    sentence_indicators = [
        " is ",
        " are ",
        " was ",
        " were ",
        " has ",
        " have ",
        " do ",
        " does ",
        " can ",
        " could ",
        " will ",
        " would ",
        " should ",
        " must ",
        " may ",
        " might ",
    ]
    for indicator in sentence_indicators:
        if indicator in text_lower:
            print(f"  包含句子结构: {indicator}")

    # 检查动词开头
    verb_starts = [
        "create",
        "generate",
        "transform",
        "install",
        "use",
        "download",
        "configure",
        "setup",
        "run",
        "execute",
    ]
    first_word = text_lower.split()[0] if text_lower.split() else ""
    if first_word in verb_starts:
        print(f"  以动词开头: {first_word}")

    # 检查是否全大写
    if prompt.isupper():
        print(f"  全大写")

    # 检查代码标识符
    import re

    if re.match(r"^[a-z]+[A-Z]", prompt) or "_" in prompt:
        if not ("_of_" in text_lower or "_with_" in text_lower or "_in_" in text_lower):
            print(f"  看起来像代码标识符")

    # 检查日期时间格式
    date_patterns = [
        r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z",
        r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}",
        r"\d{2}/\d{2}/\d{4}",
    ]
    for pattern in date_patterns:
        if re.search(pattern, prompt):
            print(f"  包含日期格式")

    # 检查是否包含AI提示词常见特征
    prompt_features = [
        "masterpiece",
        "detailed",
        "intricate",
        "sharp",
        "cinematic",
        "epic",
        "beautiful",
        "stunning",
        "amazing",
        "gorgeous",
        "4k",
        "8k",
        "hd",
        "trending",
        "artstation",
        "unreal",
        "octane",
        "vray",
        "high quality",
        "in the style of",
        "by artist",
        # 视觉相关词汇
        "image",
        "photo",
        "picture",
        "portrait",
        "landscape",
        "scene",
        "view",
        "art",
        "painting",
        "illustration",
        "digital art",
        "concept art",
        "drawing",
        "sketch",
        "render",
        "visual",
        "graphic",
        "design",
        "composition",
        "background",
        "foreground",
        "subject",
        "object",
        "character",
        "creature",
        "monster",
        "animal",
        "human",
        "person",
        "woman",
        "man",
        "girl",
        "boy",
        "child",
        "adult",
        "face",
        "head",
        "body",
        "hand",
        "eye",
        "hair",
        "nature",
        "forest",
        "mountain",
        "river",
        "ocean",
        "sky",
        "cloud",
        "sun",
        "moon",
        "star",
        "space",
        "city",
        "building",
        "house",
        "room",
        "interior",
        "exterior",
        "architecture",
        "structure",
        "vehicle",
        "car",
        "boat",
        "airplane",
        "spaceship",
        "robot",
        "fantasy",
        "sci-fi",
        "cyberpunk",
        "steampunk",
        "medieval",
        "futuristic",
        "post-apocalyptic",
        "dystopian",
        "utopian",
    ]

    has_prompt_feature = any(feature in text_lower for feature in prompt_features)
    print(f"  有提示词特征: {has_prompt_feature}")

    # 检查描述性结构
    descriptive_structures = [
        " of ",
        " with ",
        " in ",
        " on ",
        " at ",
        " by ",
        " for ",
        " and ",
        " or ",
        " but ",
        ", ",
        " - ",
        " -- ",
    ]
    has_descriptive_structure = any(struct in prompt for struct in descriptive_structures)
    print(f"  有描述性结构: {has_descriptive_structure}")

    # 检查图像生成提示词
    visual_keywords = [
        "image",
        "photo",
        "picture",
        "portrait",
        "landscape",
        "scene",
        "view",
        "art",
        "painting",
        "illustration",
        "digital art",
        "concept art",
        "drawing",
        "sketch",
        "render",
        "visual",
        "graphic",
        "composition",
        "background",
        "foreground",
        "subject",
        "object",
        "character",
        "creature",
        "monster",
        "animal",
        "human",
        "person",
        "woman",
        "man",
        "girl",
        "boy",
        "child",
        "adult",
        "face",
        "head",
        "body",
        "hand",
        "eye",
        "nature",
        "forest",
        "mountain",
        "river",
        "ocean",
        "sky",
        "cloud",
        "sun",
        "moon",
        "star",
        "space",
        "city",
        "building",
        "house",
        "room",
        "architecture",
        "structure",
        "vehicle",
        "car",
        "boat",
        "airplane",
        "spaceship",
        "robot",
        "fantasy",
        "sci-fi",
        "cyberpunk",
        "steampunk",
        "medieval",
        "futuristic",
        "post-apocalyptic",
        "dystopian",
    ]

    has_visual_keyword = any(keyword in text_lower for keyword in visual_keywords)
    print(f"  有视觉关键词: {has_visual_keyword}")

    # 检查质量修饰词
    quality_keywords = [
        "masterpiece",
        "detailed",
        "high quality",
        "professional",
        "intricate",
        "sharp",
        "cinematic",
        "epic",
        "beautiful",
        "stunning",
        "amazing",
    ]
    has_quality_keyword = any(keyword in text_lower for keyword in quality_keywords)
    print(f"  有质量关键词: {has_quality_keyword}")

    # 最后，调用原始验证
    print(f"  最终验证结果: {extractor._validate_prompt(prompt)}")
    print(f"  图像生成检查: {extractor._is_image_generation_prompt(prompt)}")
