#!/usr/bin/env python3
"""
Alert Rules Engine for Performance Metrics.

Evaluates performance metrics against configurable thresholds and generates alerts.
Supports warning/critical levels and structured alert output.
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import asdict, dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import yaml

from .performance_metrics import (
    MetricAggregation,
    MetricDimension,
    PerformanceMetricsCollector,
    get_global_collector,
)

logger = logging.getLogger(__name__)


class AlertLevel(Enum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class AlertRule:
    """Rule for evaluating metrics and generating alerts."""

    rule_id: str
    metric_dimension: MetricDimension
    condition: str  # ">", "<", ">=", "<=", "==", "!="
    threshold: float
    alert_level: AlertLevel
    description: str = ""
    cooldown_seconds: int = 300  # 5 minutes
    labels: Dict[str, str] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def evaluate(self, value: float) -> bool:
        """Evaluate if the metric value triggers this alert."""
        if self.condition == ">":
            return value > self.threshold
        elif self.condition == ">=":
            return value >= self.threshold
        elif self.condition == "<":
            return value < self.threshold
        elif self.condition == "<=":
            return value <= self.threshold
        elif self.condition == "==":
            return value == self.threshold
        elif self.condition == "!=":
            return value != self.threshold
        else:
            logger.warning(f"Unknown condition '{self.condition}' in rule {self.rule_id}")
            return False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class Alert:
    """An alert instance generated by a rule."""

    alert_id: str
    rule_id: str
    alert_level: AlertLevel
    message: str
    metric_dimension: MetricDimension
    metric_value: float
    threshold: float
    timestamp: float = field(default_factory=time.time)
    labels: Dict[str, str] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    acknowledged: bool = False

    def to_dict(self) -> Dict[str, Any]:
        result = asdict(self)
        result["alert_level"] = self.alert_level.value
        result["metric_dimension"] = self.metric_dimension.value
        return result


class AlertEngine:
    """Engine that evaluates metrics against alert rules."""

    def __init__(self, config_path: Optional[Path] = None):
        self.collector = get_global_collector()
        self.rules: Dict[str, AlertRule] = {}
        self.alerts: Dict[str, Alert] = {}  # active alerts keyed by alert_id
        self.last_evaluation: Dict[str, float] = {}  # rule_id -> last trigger time

        # Load default rules
        self._load_default_rules()

        # Determine config path: use provided path, otherwise check default location
        actual_config_path = config_path
        if actual_config_path is None:
            # Default config path: mini-agent/config/alert_rules.yaml
            default_config = Path(__file__).parent.parent.parent / "config" / "alert_rules.yaml"
            if default_config.exists():
                actual_config_path = default_config
                logger.info(f"Using default alert config: {default_config}")
            else:
                logger.info("No alert config file found, using built-in defaults only")

        # Load config if path exists
        if actual_config_path and actual_config_path.exists():
            self.load_config(actual_config_path)

        logger.info(f"Alert engine initialized with {len(self.rules)} rules")

    def _load_default_rules(self) -> None:
        """Load minimal default alert rules."""
        default_rules = [
            AlertRule(
                rule_id="queue_length_high",
                metric_dimension=MetricDimension.QUEUE_LENGTH,
                condition=">",
                threshold=10.0,
                alert_level=AlertLevel.WARNING,
                description="Queue length exceeds warning threshold",
            ),
            AlertRule(
                rule_id="queue_length_critical",
                metric_dimension=MetricDimension.QUEUE_LENGTH,
                condition=">",
                threshold=20.0,
                alert_level=AlertLevel.CRITICAL,
                description="Queue length exceeds critical threshold",
            ),
            AlertRule(
                rule_id="failure_rate_high",
                metric_dimension=MetricDimension.FAILURE_RATE,
                condition=">",
                threshold=0.1,  # 10%
                alert_level=AlertLevel.WARNING,
                description="Failure rate exceeds warning threshold",
            ),
            AlertRule(
                rule_id="failure_rate_critical",
                metric_dimension=MetricDimension.FAILURE_RATE,
                condition=">",
                threshold=0.3,  # 30%
                alert_level=AlertLevel.CRITICAL,
                description="Failure rate exceeds critical threshold",
            ),
            AlertRule(
                rule_id="response_time_slow",
                metric_dimension=MetricDimension.RESPONSE_TIME,
                condition=">",
                threshold=300.0,  # 5 minutes
                alert_level=AlertLevel.WARNING,
                description="Response time exceeds warning threshold",
            ),
            AlertRule(
                rule_id="response_time_critical",
                metric_dimension=MetricDimension.RESPONSE_TIME,
                condition=">",
                threshold=600.0,  # 10 minutes
                alert_level=AlertLevel.CRITICAL,
                description="Response time exceeds critical threshold",
            ),
            AlertRule(
                rule_id="heartbeat_stale",
                metric_dimension=MetricDimension.HEARTBEAT_FRESHNESS,
                condition=">",
                threshold=300.0,  # 5 minutes
                alert_level=AlertLevel.WARNING,
                description="Heartbeat freshness exceeds warning threshold",
            ),
            AlertRule(
                rule_id="heartbeat_critical",
                metric_dimension=MetricDimension.HEARTBEAT_FRESHNESS,
                condition=">",
                threshold=600.0,  # 10 minutes
                alert_level=AlertLevel.CRITICAL,
                description="Heartbeat freshness exceeds critical threshold",
            ),
        ]

        for rule in default_rules:
            self.add_rule(rule)

    def add_rule(self, rule: AlertRule) -> None:
        """Add an alert rule."""
        self.rules[rule.rule_id] = rule

    def remove_rule(self, rule_id: str) -> None:
        """Remove an alert rule."""
        if rule_id in self.rules:
            del self.rules[rule_id]

    def load_config(self, config_path: Path) -> None:
        """Load alert rules from YAML configuration."""
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                config = yaml.safe_load(f)

            if not config or "alert_rules" not in config:
                return

            for rule_config in config["alert_rules"]:
                try:
                    rule = AlertRule(
                        rule_id=rule_config["rule_id"],
                        metric_dimension=MetricDimension[rule_config["metric_dimension"]],
                        condition=rule_config["condition"],
                        threshold=float(rule_config["threshold"]),
                        alert_level=AlertLevel[rule_config["alert_level"]],
                        description=rule_config.get("description", ""),
                        cooldown_seconds=rule_config.get("cooldown_seconds", 300),
                        labels=rule_config.get("labels", {}),
                        metadata=rule_config.get("metadata", {}),
                    )
                    self.add_rule(rule)
                except (KeyError, ValueError) as e:
                    logger.error(f"Failed to load alert rule {rule_config}: {e}")

            logger.info(f"Loaded {len(config.get('alert_rules', []))} rules from {config_path}")
        except Exception as e:
            logger.error(f"Failed to load alert config {config_path}: {e}")

    def evaluate_all(self) -> List[Alert]:
        """Evaluate all rules against current metrics."""
        new_alerts = []

        for rule_id, rule in self.rules.items():
            # Check cooldown
            last_trigger = self.last_evaluation.get(rule_id, 0)
            if time.time() - last_trigger < rule.cooldown_seconds:
                continue

            # Get relevant metric aggregations
            aggregations = self.collector.get_aggregations(
                dimension=rule.metric_dimension,
                labels=rule.labels,
            )

            if not aggregations:
                continue

            # Evaluate each aggregation
            for agg in aggregations:
                # Use average value for evaluation
                value = agg.avg

                if rule.evaluate(value):
                    # Generate alert
                    alert_id = f"{rule_id}_{int(time.time())}"
                    alert = Alert(
                        alert_id=alert_id,
                        rule_id=rule_id,
                        alert_level=rule.alert_level,
                        message=f"{rule.description}: {value:.2f} {rule.condition} {rule.threshold}",
                        metric_dimension=rule.metric_dimension,
                        metric_value=value,
                        threshold=rule.threshold,
                        labels={**rule.labels, **agg.labels},
                        metadata={
                            **rule.metadata,
                            "aggregation": agg.to_dict(),
                            "rule": rule.to_dict(),
                        },
                    )

                    # Check if similar alert already active
                    existing_alert = self._find_similar_alert(alert)
                    if existing_alert:
                        # Update timestamp
                        existing_alert.timestamp = time.time()
                    else:
                        self.alerts[alert_id] = alert
                        new_alerts.append(alert)

                    self.last_evaluation[rule_id] = time.time()

        return new_alerts

    def _find_similar_alert(self, alert: Alert) -> Optional[Alert]:
        """Find similar active alert (same rule, labels, and dimension)."""
        for active_alert in self.alerts.values():
            if (
                active_alert.rule_id == alert.rule_id
                and active_alert.metric_dimension == alert.metric_dimension
                and active_alert.labels == alert.labels
            ):
                return active_alert
        return None

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Mark an alert as acknowledged."""
        if alert_id in self.alerts:
            self.alerts[alert_id].acknowledged = True
            return True
        return False

    def resolve_alert(self, alert_id: str) -> bool:
        """Remove an alert (considered resolved)."""
        if alert_id in self.alerts:
            del self.alerts[alert_id]
            return True
        return False

    def get_active_alerts(self, level: Optional[AlertLevel] = None) -> List[Alert]:
        """Get all active alerts, optionally filtered by level."""
        alerts = list(self.alerts.values())
        if level:
            alerts = [a for a in alerts if a.alert_level == level]
        return sorted(alerts, key=lambda a: a.timestamp, reverse=True)

    def export_summary(self) -> Dict[str, Any]:
        """Export summary of current alert state."""
        active_alerts = self.get_active_alerts()

        return {
            "timestamp": time.time(),
            "active_alert_count": len(active_alerts),
            "rule_count": len(self.rules),
            "alerts_by_level": {
                level.value: len([a for a in active_alerts if a.alert_level == level])
                for level in AlertLevel
            },
            "active_alerts": [a.to_dict() for a in active_alerts[:20]],  # limit output
        }

    def export_json(self, filepath: Optional[Path] = None) -> Dict[str, Any]:
        """Export alert state as JSON-serializable dict."""
        data = {
            "export_timestamp": time.time(),
            "export_version": "1.0",
            "rules": [r.to_dict() for r in self.rules.values()],
            "active_alerts": [a.to_dict() for a in self.alerts.values()],
            "last_evaluations": self.last_evaluation,
        }

        if filepath:
            filepath.parent.mkdir(parents=True, exist_ok=True)
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            logger.info(f"Alert state exported to {filepath}")

        return data


# Global alert engine instance
_global_alert_engine: Optional[AlertEngine] = None


def get_global_alert_engine() -> AlertEngine:
    """Get global alert engine instance."""
    global _global_alert_engine
    if _global_alert_engine is None:
        _global_alert_engine = AlertEngine()
    return _global_alert_engine


def evaluate_alerts() -> List[Alert]:
    """Evaluate alerts using the global engine."""
    engine = get_global_alert_engine()
    return engine.evaluate_all()
