#!/usr/bin/env python3
"""
知识蒸馏持续归档
扫描 Athena 统一 runtime root，将执行报告自动转化为 SKILL.md 积木
写入 COGNITIVE_DNA.md

执行: python3 scripts/knowledge_distillation.py
"""

import os
import re
from datetime import datetime
from pathlib import Path

RUNTIME_ROOT = Path(os.getenv("ATHENA_RUNTIME_ROOT", "/Volumes/1TB-M2/openclaw"))
SOURCE_DIR = RUNTIME_ROOT
TARGET_DIR = RUNTIME_ROOT / "skills"
COGNITIVE_DNA = RUNTIME_ROOT / "COGNITIVE_DNA.md"


def scan_reports():
    """扫描完成文件夹中的报告"""
    reports = []

    # 扫描 memory 目录
    memory_dir = SOURCE_DIR / "memory"
    if memory_dir.exists():
        for md_file in memory_dir.glob("*.md"):
            content = md_file.read_text()
            # 识别执行报告（包含结果、测试、验证等关键词）
            if any(kw in content.lower() for kw in ["测试", "验证", "结果", "完成", "饱和攻击"]):
                reports.append(
                    {
                        "source": str(md_file.relative_to(SOURCE_DIR)),
                        "filename": md_file.name,
                        "content": content[:2000],  # 截取前2000字符
                    }
                )

    # 扫描 skills 目录
    skills_dir = SOURCE_DIR / "skills"
    if skills_dir.exists():
        for skill_dir in skills_dir.glob("openhuman-*"):
            if skill_dir.is_dir():
                skill_yaml = skill_dir / "skill.yaml"
                if skill_yaml.exists():
                    reports.append(
                        {
                            "source": str(skill_dir.relative_to(SOURCE_DIR)),
                            "filename": skill_yaml.name,
                            "content": skill_yaml.read_text(),
                        }
                    )

    return reports


def extract_skill_metadata(content: str, source: str) -> dict:
    """从报告内容提取 skill 元数据"""
    metadata = {"skill_id": "", "name": "", "description": "", "tags": [], "source": source}

    # 从文件名提取
    if "openhuman-" in source:
        metadata["skill_id"] = source.split("/")[-1]
        metadata["name"] = metadata["skill_id"].replace("-", " ").title()

    # 从内容提取描述
    lines = content.split("\n")
    for line in lines[:10]:
        if line.startswith("# "):
            metadata["description"] = line[2:].strip()
            break

    # 提取标签
    tags = re.findall(r"#(\w+)", content[:500])
    metadata["tags"] = list(set(tags))[:5]

    return metadata


def generate_skill_md(metadata: dict) -> str:
    """生成 SKILL.md 内容"""
    skill_id = metadata.get("skill_id", "unknown-skill")
    name = metadata.get("name", "Unknown Skill")
    description = metadata.get("description", "Auto-distilled skill from execution report")
    tags = metadata.get("tags", [])

    return f"""# {name}

**Skill ID**: `{skill_id}`  
**Source**: {metadata.get("source", "unknown")}  
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Description

{description}

## Tags

{", ".join([f"`{tag}`" for tag in tags]) if tags else "_No tags_"}

## Metadata

| Field | Value |
|-------|-------|
| Skill ID | {skill_id} |
| Source | {metadata.get("source", "unknown")} |
| Generated | {datetime.now().isoformat()} |

## Notes

- Auto-generated from knowledge distillation pipeline
- Part of OpenHuman cognitive architecture
"""


def update_cognitive_dna(skills: list):
    """更新 COGNITIVE_DNA.md"""

    # 读取现有内容
    existing = ""
    if COGNITIVE_DNA.exists():
        existing = COGNITIVE_DNA.read_text()

    # 生成新内容
    skills_section = "\n".join(
        [
            f"- **{s['skill_id']}**: {s.get('description', 'N/A')}"
            for s in skills
            if s.get("skill_id")
        ]
    )

    new_content = f"""# OpenClaw COGNITIVE DNA

**Last Updated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Distilled Skills

{skills_section if skills_section else "- No skills distilled yet"}

---

*Auto-generated by knowledge distillation pipeline*
"""

    COGNITIVE_DNA.write_text(new_content)
    print(f"   ✅ COGNITIVE_DNA.md 已更新: {len(skills)} skills")


def run_distillation():
    """执行知识蒸馏"""
    print("🧠 知识蒸馏持续归档启动")
    print(f"   扫描目录: {SOURCE_DIR}")
    print("-" * 50)

    # 扫描报告
    reports = scan_reports()
    print(f"   发现报告: {len(reports)} 个")

    # 提取元数据
    skills = []
    for report in reports:
        metadata = extract_skill_metadata(report["content"], report["source"])
        if metadata.get("skill_id"):
            skills.append(metadata)

    print(f"   提取 Skill: {len(skills)} 个")

    # 生成 SKILL.md
    for skill in skills:
        skill_dir = TARGET_DIR / skill["skill_id"]
        skill_dir.mkdir(parents=True, exist_ok=True)

        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            skill_md.write_text(generate_skill_md(skill))
            print(f"   ✅ 生成: {skill['skill_id']}/SKILL.md")

    # 更新 COGNITIVE_DNA
    if skills:
        update_cognitive_dna(skills)

    print("-" * 50)
    print(f"📦 归档完成: {len(skills)} skills")

    return skills


if __name__ == "__main__":
    run_distillation()
